// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSiQwylDva_xpLCsiC9fZLc9R002U1ARQ',
    appId: '1:560762092474:web:dce5f4891ff5433ee0bb83',
    messagingSenderId: '560762092474',
    projectId: 'movietickets-3ddad',
    authDomain: 'movietickets-3ddad.firebaseapp.com',
    storageBucket: 'movietickets-3ddad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzA8Jwxmv9XE1QAQg57vmD-nCDBDO_ccA',
    appId: '1:560762092474:android:6682c89e92b78726e0bb83',
    messagingSenderId: '560762092474',
    projectId: 'movietickets-3ddad',
    storageBucket: 'movietickets-3ddad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKqFBHp8PLGPQ0stD0kkL9afwB45uZkbM',
    appId: '1:560762092474:ios:6873b6f9c2f442dde0bb83',
    messagingSenderId: '560762092474',
    projectId: 'movietickets-3ddad',
    storageBucket: 'movietickets-3ddad.appspot.com',
    iosBundleId: 'com.example.moviesTicketBookingWebsite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKqFBHp8PLGPQ0stD0kkL9afwB45uZkbM',
    appId: '1:560762092474:ios:6ef8ba50602ff26ae0bb83',
    messagingSenderId: '560762092474',
    projectId: 'movietickets-3ddad',
    storageBucket: 'movietickets-3ddad.appspot.com',
    iosBundleId: 'com.example.moviesTicketBookingWebsite.RunnerTests',
  );
}
